// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qUhMMIoY7GZUmTUHc0DaW9kJW7Htn-E',
    appId: '1:1016462639289:web:509008210e6803613f1b68',
    messagingSenderId: '1016462639289',
    projectId: 'fir-c1659',
    authDomain: 'fir-c1659.firebaseapp.com',
    databaseURL: 'https://fir-c1659-default-rtdb.firebaseio.com',
    storageBucket: 'fir-c1659.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCR6IfcvSGzuugtPLCeS5t2CUc6pmB68',
    appId: '1:1016462639289:android:68bd9475d6a5089e3f1b68',
    messagingSenderId: '1016462639289',
    projectId: 'fir-c1659',
    databaseURL: 'https://fir-c1659-default-rtdb.firebaseio.com',
    storageBucket: 'fir-c1659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgtHm8QkWXFZRxn8rC5kIcOp-q4TuS5jc',
    appId: '1:1016462639289:ios:293b60571e62e0503f1b68',
    messagingSenderId: '1016462639289',
    projectId: 'fir-c1659',
    databaseURL: 'https://fir-c1659-default-rtdb.firebaseio.com',
    storageBucket: 'fir-c1659.firebasestorage.app',
    iosClientId: '1016462639289-el87u6s5ghlm3821lvarkpsgio951it7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveGlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgtHm8QkWXFZRxn8rC5kIcOp-q4TuS5jc',
    appId: '1:1016462639289:ios:293b60571e62e0503f1b68',
    messagingSenderId: '1016462639289',
    projectId: 'fir-c1659',
    databaseURL: 'https://fir-c1659-default-rtdb.firebaseio.com',
    storageBucket: 'fir-c1659.firebasestorage.app',
    iosClientId: '1016462639289-el87u6s5ghlm3821lvarkpsgio951it7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveGlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9qUhMMIoY7GZUmTUHc0DaW9kJW7Htn-E',
    appId: '1:1016462639289:web:5a4e8a85c401ffe73f1b68',
    messagingSenderId: '1016462639289',
    projectId: 'fir-c1659',
    authDomain: 'fir-c1659.firebaseapp.com',
    databaseURL: 'https://fir-c1659-default-rtdb.firebaseio.com',
    storageBucket: 'fir-c1659.firebasestorage.app',
  );
}
